services:
  app:
    build: ./app
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./app/data:/app/data
    command: ["python", "main.py"]

  # To-Do: Crear un servicio con tu servidor. Debe tener:
  # - Los ficheros de Python necesarios para tu servidor.
  # - Un Dockerfile que instale las dependencias necesarias.
  # - Un comando que inicie tu servidor.
  # - La SERVER_URL del servidor vLLM y el API_KEY como variables de entorno.
